import { badRequest, validationError } from './errors.js';

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

function typeError(field, spec, value) {
  return { field, message: `must be of type ${spec.type}`, received: value };
}

function checkType(field, spec, value) {
  switch (spec.type) {
    case 'string':
      return typeof value === 'string' && value.trim().length > 0 ? null : { field, message: 'must be a non-empty string', received: value };
    case 'integer':
      return Number.isInteger(value) ? null : typeError(field, spec, value);
    case 'number':
      return typeof value === 'number' && Number.isFinite(value) ? null : typeError(field, spec, value);
    case 'boolean':
      return typeof value === 'boolean' ? null : typeError(field, spec, value);
    case 'date':
      return typeof value === 'string' && DATE_RE.test(value) && !Number.isNaN(Date.parse(value))
        ? null
        : { field, message: 'must be a date in YYYY-MM-DD format', received: value };
    case 'datetime':
      return typeof value === 'string' && !Number.isNaN(Date.parse(value))
        ? null
        : { field, message: 'must be an ISO-8601 date-time string', received: value };
    default:
      return null;
  }
}

/**
 * Validate a request body against a resource definition.
 * mode: 'create' (required + defaults), 'replace' (required, no defaults for
 * missing optional fields beyond spec defaults) or 'patch' (partial).
 */
export function validateBody(resource, body, mode, store) {
  if (body === undefined || body === null || typeof body !== 'object' || Array.isArray(body)) {
    throw badRequest('Request body must be a JSON object');
  }

  const errors = [];
  const result = {};
  const fields = resource.fields;

  for (const key of Object.keys(body)) {
    if (key === 'id' || key === 'createdAt' || key === 'updatedAt') {
      errors.push({ field: key, message: 'is read-only' });
    } else if (!fields[key]) {
      errors.push({ field: key, message: 'is not a recognised field' });
    } else if (fields[key].auto) {
      errors.push({ field: key, message: 'is generated by the server and cannot be set' });
    }
  }

  if (mode === 'patch' && Object.keys(body).length === 0) {
    throw badRequest('PATCH body must contain at least one field');
  }

  for (const [field, spec] of Object.entries(fields)) {
    if (spec.auto) continue;
    let value = body[field];

    if (value === undefined || value === null) {
      if (mode === 'patch') continue;
      if (spec.default !== undefined) {
        result[field] = spec.default;
        continue;
      }
      if (spec.required) errors.push({ field, message: 'is required' });
      else result[field] = null;
      continue;
    }

    const typeProblem = checkType(field, spec, value);
    if (typeProblem) {
      errors.push(typeProblem);
      continue;
    }
    if (spec.enum && !spec.enum.includes(value)) {
      errors.push({ field, message: `must be one of: ${spec.enum.join(', ')}`, received: value });
      continue;
    }
    if (spec.ref && !store.collection(spec.ref).has(value)) {
      errors.push({ field, message: `references ${spec.ref}/${value} which does not exist`, received: value });
      continue;
    }
    result[field] = value;
  }

  if (errors.length) throw validationError(errors);
  return result;
}

export function parseId(raw) {
  const id = Number(raw);
  if (!Number.isInteger(id) || id < 1) throw badRequest(`Path parameter 'id' must be a positive integer, received '${raw}'`);
  return id;
}
